### PR TITLE
Support setting per-role config with ALTER ROLE SET

### PR DESCRIPTION
**Pull request by jfleury-gorgias**
Upstream PR: [Squarespace/pgbedrock#73](https://github.com/Squarespace/pgbedrock/pull/73)

---

:warning: With this change, pgbedrock becomes the authority on user config and will override any existing config (or reset them if they are not set in the configuration).

### CODE REVIEW

**Comment by jfleury-gorgias** [comment]
I still need to make sure this works as expected on staging.

**Comment by jfleury-gorgias** [comment]
So this was successfully tested on staging.

Here are the logs from pgbedrock:

```
--------------------------------
--- Configuring attributes -----
--------------------------------

ALTER ROLE "gorgias" SET statement_timeout="10min"; -- Previous value: 5min
ALTER ROLE "gorgias" RESET idle_in_transaction_session_timeout; -- Previous value: 2min
```

And how the settings have been changed (from `SELECT usename,useconfig FROM pg_shadow WHERE useconfig IS NOT NULL ORDER BY usename;`):

```
     usename     |                            useconfig
 ----------------+------------------------------------------------------------------
  debezium       | {idle_in_transaction_session_timeout=2min}
- gorgias        | {statement_timeout=5min,idle_in_transaction_session_timeout=2min}
+ gorgias        | {statement_timeout=10min}
  gorgias_web    | {statement_timeout=55s,gin_pending_list_limit=512kB}
  gorgias_worker | {statement_timeout=55s,gin_pending_list_limit=512kB}
  periscope      | {statement_timeout=55s,idle_in_transaction_session_timeout=2min}
```

**Comment by jfleury-gorgias** [comment]
I created gorgias/gorgias#12995 if you want to see the change in the config.

**Review by FlipEnergy — DISMISSED** [review]
This is good work, Johan. LGTM.

**Comment by jfleury-gorgias** [comment]
@FlipEnergy I just imported [your commit from the upstream PR](https://github.com/Squarespace/pgbedrock/pull/72/commits/ac450e97288e9af14b167b41548492874462e39e).

**Review by deadlytea — COMMENTED** [review]
Would be nice to have some tests for the byte/duration parse logic before we put this in, also I'm not a fan of `configs` as the wording choice as it makes me think of a set of config structures, not a set of parameters, but I won't block on that we can update if we can think of something better

**Comment by jfleury-gorgias** [comment]
> Would be nice to have some tests for the byte/duration parse logic before we put this in

Done and it helped me find some bugs, I should’ve done that earlier.

**Review by deadlytea — APPROVED** [review]
LGTM

**Pull request merged**
